"""Render the NIST adversarial-ML coverage matrix as a report.

A thin presentation layer over core/nist.coverage(): it turns the per-cell coverage
into a terminal summary and a Markdown document, so the CLI stays a dispatcher and the
matrix logic stays in core/nist. No probe is hard-coded here; it reads the live registry.
"""
from __future__ import annotations

from .nist import coverage as _coverage

_MARK = {"covered": "✓ covered", "partial": "~ partial",
         "out_of_scope": "· out of runtime scope", "gap": "✗ gap"}


def build(probes) -> dict:
    return _coverage(probes)


def render_text(cov: dict) -> str:
    c = cov["counts"]
    L = ["", "  NIST AI 100-2e2025 adversarial-ML coverage",
         f"  covered {c.get('covered', 0)} · partial {c.get('partial', 0)} · "
         f"out-of-scope {c.get('out_of_scope', 0)} · gaps {c.get('gap', 0)}", ""]
    for cell in cov["cells"]:
        mark = _MARK.get(cell["status"], cell["status"])
        line = f"    {cell['id']:14} {mark:24} {cell['name']} [{cell['stage']}]"
        L.append(line)
        if cell["note"]:
            L.append(f"        {cell['note']}")
    gaps = [x for x in cov["cells"] if x["status"] == "gap"]
    if gaps:
        L.append("")
        L.append("  GAPS (runtime-scannable, not yet covered): "
                 + ", ".join(x["id"] for x in gaps))
    return "\n".join(L)


def render_markdown(cov: dict) -> str:
    c = cov["counts"]
    out = ["# NIST adversarial-ML coverage matrix", "",
           "Redline mapped to NIST AI 100-2e2025 (*Adversarial Machine Learning: A Taxonomy "
           "and Terminology of Attacks and Mitigations*). Generated by `redline coverage`.", "",
           f"**Summary:** {c.get('covered', 0)} covered, {c.get('partial', 0)} partial, "
           f"{c.get('out_of_scope', 0)} out of runtime scope, {c.get('gap', 0)} gaps.", "",
           "A black-box runtime scanner can exercise inference-time attack cells. Training-time "
           "cells (poisoning, backdoors, supply chain) are process and provenance controls, "
           "partially addressed by `redline inventory`, and are marked out of runtime scope with "
           "the reason rather than silently claimed.", "",
           "| NIST ID | attack | stage | status | note |",
           "|---------|--------|-------|--------|------|"]
    for cell in cov["cells"]:
        out.append(f"| {cell['id']} | {cell['name']} | {cell['stage']} | "
                   f"{cell['status']} | {cell['note']} |")
    out += ["", "## NIST AI 600-1 GenAI Profile risks evidenced", ""]
    for rid, name in cov["genai_profile"].items():
        out.append(f"- **§{rid} {name}**")
    out += ["", "## NIST AI RMF 1.0",
            "Primary evidence for **MEASURE 2.7** (security and resilience) and "
            "**MEASURE 2.10** (privacy), feeding **MANAGE 1.3 / 2.3 / 4.1** for response "
            "and recovery.", ""]
    return "\n".join(out)
